version: "3"
services:
  proxy:
    image: ubuntu/squid
    ports:
      - "3128:3128"
    environment:
      - TZ=UTC
    volumes:
      - ./squid.conf:${HOME}/squid/squid.conf
    configs:
      - source: squid
        target: ${HOME}/squid/squid.conf

configs:
  squid:
    file: ./squid.conf
